### ISSUE TITLE
Latest main fails to build on rhel9

### ISSUE THREAD

**Issue by igsilya** [retis-org/retis#359]
Commit  https://github.com/retis-org/retis/commit/29d7fc95100187ad74ebd29fb6d57175e7b25220 fails to build on rhel 9.3 while v1.3.1 tag builds just fine.

```
[root@rhel9 retis]# CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true RUST_BACKTRACE=full cargo build --release
   Compiling proc-macro2 v1.0.70
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.151
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling pkg-config v0.3.27
   Compiling syn v1.0.109
   Compiling thiserror v1.0.50
   Compiling memchr v2.6.4
   Compiling equivalent v1.0.1
   Compiling pin-utils v0.1.0
   Compiling bitflags v1.3.2
   Compiling hashbrown v0.14.3
   Compiling serde v1.0.193
   Compiling winnow v0.5.28
   Compiling heck v0.4.1
   Compiling toml_datetime v0.6.5
   Compiling once_cell v1.19.0
   Compiling regex-syntax v0.8.2
   Compiling bitflags v2.4.1
   Compiling rustix v0.38.28
   Compiling anyhow v1.0.75
   Compiling rustversion v1.0.14
   Compiling glob v0.3.1
   Compiling linux-raw-sys v0.4.12
   Compiling camino v1.1.6
   Compiling prettyplease v0.2.15
   Compiling serde_json v1.0.108
   Compiling semver v1.0.20
   Compiling minimal-lexical v0.2.1
   Compiling ryu v1.0.16
   Compiling lazy_static v1.4.0
   Compiling clap_lex v0.6.0
   Compiling fnv v1.0.7
   Compiling ident_case v1.0.1
   Compiling anstyle v1.0.4
   Compiling strsim v0.10.0
   Compiling itoa v1.0.10
   Compiling utf8parse v0.2.1
   Compiling libloading v0.7.4
   Compiling either v1.9.0
   Compiling home v0.5.5
   Compiling fastrand v2.0.1
   Compiling anstyle-query v1.0.2
   Compiling anstyle-parse v0.2.3
   Compiling bindgen v0.69.1
   Compiling colorchoice v1.0.0
   Compiling libloading v0.6.7
   Compiling shlex v1.3.0
   Compiling scroll v0.11.0
   Compiling clap_builder v4.4.11
   Compiling peeking_take_while v0.1.2
   Compiling crc32fast v1.3.2
   Compiling log v0.4.20
   Compiling byteorder v1.5.0
   Compiling rustc-hash v1.1.0
   Compiling lazycell v1.3.0
   Compiling anstream v0.6.5
   Compiling powerfmt v0.2.0
   Compiling signal-hook v0.3.17
   Compiling time-core v0.1.2
   Compiling adler v1.0.2
   Compiling unsafe-libyaml v0.2.10
   Compiling plain v0.2.3
   Compiling time-macros v0.2.15
   Compiling miniz_oxide v0.7.1
   Compiling deranged v0.3.10
   Compiling bimap v0.6.3
   Compiling path-clean v1.0.1
   Compiling termcolor v1.4.0
   Compiling elf v0.7.4
   Compiling byteorder_slice v3.0.0
   Compiling memoffset v0.7.1
   Compiling memoffset v0.9.0
   Compiling btf-rs v1.0.0
   Compiling clang-sys v1.6.1
   Compiling aho-corasick v1.1.2
   Compiling nom v7.1.3
   Compiling indexmap v2.1.0
   Compiling quote v1.0.33
   Compiling flate2 v1.0.28
   Compiling syn v2.0.41
   Compiling time v0.3.30
   Compiling errno v0.2.8
   Compiling nix v0.27.1
   Compiling signal-hook-registry v1.4.1
   Compiling pager v0.16.1
   Compiling regex-automata v0.4.3
   Compiling cc v1.0.83
   Compiling nix v0.26.4
   Compiling num_cpus v1.16.0
   Compiling memmap2 v0.5.10
   Compiling memmap2 v0.9.0
   Compiling toml_edit v0.19.15
   Compiling cexpr v0.6.0
   Compiling tempfile v3.8.1
   Compiling which v4.4.2
   Compiling vsprintf v2.0.0
   Compiling proc-macro-crate v1.3.1
   Compiling strum_macros v0.24.3
   Compiling derive-into-owned v0.2.0
   Compiling regex v1.10.2
   Compiling num_enum_derive v0.5.11
   Compiling darling_core v0.20.3
   Compiling pcap v1.1.0
   Compiling libbpf-sys v1.2.1+v1.2.0
   Compiling num_enum v0.5.11
   Compiling serde_derive v1.0.193
   Compiling thiserror-impl v1.0.50
   Compiling clap_derive v4.4.7
   Compiling scroll_derive v0.11.1
   Compiling retis-derive v1.3.0 (/root/retis/retis-derive)
   Compiling darling_macro v0.20.3
   Compiling darling v0.20.3
   Compiling serde_with_macros v3.4.0
   Compiling pcap-file v2.0.0
   Compiling caps v0.5.5
   Compiling libbpf-rs v0.22.0
   Compiling clap v4.4.11
   Compiling clap_complete v4.4.6
   Compiling cargo-platform v0.1.5
   Compiling serde_yaml v0.9.27
   Compiling serde_with v3.4.0
   Compiling cargo_metadata v0.15.4
   Compiling libbpf-cargo v0.22.0
   Compiling retis v1.3.1 (/root/retis)
error: failed to run custom build command for `retis v1.3.1 (/root/retis)`

Caused by:
  process didn't exit successfully: `/root/retis/target/release/build/retis-6e193fcc0f40b7ee/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-changed=src/core/bpf_sys/include/bpf-sys.h
  cargo:rerun-if-changed=src/core/bpf_sys/include/linux/bpf.h
  cargo:rerun-if-changed=/usr/include/linux/types.h
  cargo:rerun-if-changed=/usr/include/asm/types.h
  cargo:rerun-if-changed=/usr/include/asm-generic/types.h
  cargo:rerun-if-changed=/usr/include/asm-generic/int-ll64.h
  cargo:rerun-if-changed=/usr/include/asm/bitsperlong.h
  cargo:rerun-if-changed=/usr/include/asm-generic/bitsperlong.h
  cargo:rerun-if-changed=/usr/include/linux/posix_types.h
  cargo:rerun-if-changed=/usr/include/linux/stddef.h
  cargo:rerun-if-changed=/usr/include/asm/posix_types.h
  cargo:rerun-if-changed=/usr/include/asm/posix_types_64.h
  cargo:rerun-if-changed=/usr/include/asm-generic/posix_types.h
  cargo:rerun-if-changed=/usr/include/asm/bitsperlong.h
  cargo:rerun-if-changed=src/core/bpf_sys/include/linux/bpf_common.h
  cargo:rerun-if-changed=src/core/bpf_sys/include/linux/filter.h
  cargo:rerun-if-changed=/usr/include/linux/types.h
  cargo:rerun-if-changed=src/core/bpf_sys/include/linux/bpf_common.h

  --- stderr
  Failed to run rustfmt: cannot find binary path (non-fatal, continuing)
  thread 'main' panicked at 'failed to generate `src/core/probe/kernel/bpf/.out/kprobe.bpf.o`

  Caused by:
      0: Failed to generate skeleton for src/core/probe/kernel/bpf/.out/kprobe.bpf.o
      1: No such file or directory (os error 2)', build.rs:46:9
  stack backtrace:
     0:     0x56256594c961 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf66164b97344d0a2
     1:     0x562565973b9f - core::fmt::write::hbb74f2248ccd4395
     2:     0x562565949631 - std::io::Write::write_fmt::hed9c5edae1eac7b4
     3:     0x56256594c775 - std::sys_common::backtrace::print::hc9a6bb05c1f66b1d
     4:     0x56256594dc17 - std::panicking::default_hook::{{closure}}::h617bee45ce760ff9
     5:     0x56256594da04 - std::panicking::default_hook::hfb5619c23c95dafb
     6:     0x56256594e0cc - std::panicking::rust_panic_with_hook::h07253f826b957552
     7:     0x56256594dfc7 - std::panicking::begin_panic_handler::{{closure}}::hfde4141a9de96c92
     8:     0x56256594cd96 - std::sys_common::backtrace::__rust_end_short_backtrace::he15cde744ac23f89
     9:     0x56256594dd12 - rust_begin_unwind
    10:     0x5625650f1b33 - core::panicking::panic_fmt::h2494779393265ba8
    11:     0x5625650f646d - build_script_build::gen_probe_skel::h94a31aa8344a1565
                                 at /root/retis/build.rs:46:9
    12:     0x5625650f6a9a - build_script_build::main::h8ef4f968fad49f97
                                 at /root/retis/build.rs:74:5
    13:     0x5625650f488b - core::ops::function::FnOnce::call_once::hd29adacf1329008b
                                 at /builddir/build/BUILD/rustc-1.71.1-src/library/core/src/ops/function.rs:250:5
    14:     0x5625650f480e - std::sys_common::backtrace::__rust_begin_short_backtrace::h4dc7489dfe364ed9
                                 at /builddir/build/BUILD/rustc-1.71.1-src/library/std/src/sys_common/backtrace.rs:135:18
    15:     0x5625650f3541 - std::rt::lang_start::{{closure}}::hece521377cea91a3
                                 at /builddir/build/BUILD/rustc-1.71.1-src/library/std/src/rt.rs:166:18
    16:     0x562565944885 - std::rt::lang_start_internal::he62005167fe2938d
    17:     0x5625650f351a - std::rt::lang_start::h325ad00d3fb552ec
                                 at /builddir/build/BUILD/rustc-1.71.1-src/library/std/src/rt.rs:165:17
    18:     0x5625650f6c4e - main
    19:     0x7f46c7a3feb0 - __libc_start_call_main
    20:     0x7f46c7a3ff60 - __libc_start_main@GLIBC_2.2.5
    21:     0x5625650f22d5 - _start
    22:                0x0 - <unknown>
```

**Comment by atenart** [comment]
Looks like BPF object files are not generated and the build fails because of this. Since 43f3165f5349 the build is handled in a Makefile and BPF object files are not built using `cargo` anymore.

You should use `make` instead to compile Retis now, or to only build the BPF objects, `make ebpf` and then `cargo build` if there is any reason you need to call cargo manually. (Note that `make -jX` can be used now, wch greatly improve build time).

A better error message for the above issue is being worked on atm, see #358.

**Comment by igsilya** [comment]
@atenart Ack.  You may treat this one as a documentation bug then, since building retis with `make` doesn't seem to be documented anywhere, AFAICT.  docs/install.md says that I need to build with cargo.

Also, `jq` is now a build requirement and this is also not documented.

**Comment by igsilya** [comment]
> Note that make -jX can be used now, which greatly improves build time

It doesn't seem to work for me.  I run make -j40 and see a single rustc process running in the top and the build takes enormous amount of time.  If I build with cargo directly, it uses a lot of cores in parallel and the build takes about 50 seconds.

**Comment by vlrpl** [comment]
> @atenart Ack. You may treat this one as a documentation bug then, since building retis with `make` doesn't seem to be documented anywhere, AFAICT. docs/install.md says that I need to build with cargo.
> 
> Also, `jq` is now a build requirement and this is also not documented.

[latest doc](https://retis.readthedocs.io/en/latest/install/#from-sources) should mention both.
Any chance the doc was pointing to stable (default)?

**Comment by vlrpl** [comment]
> > Note that make -jX can be used now, which greatly improves build time
> 
> It doesn't seem to work for me. I run make -j40 and see a single rustc process running in the top and the build takes enormous amount of time. If I build with cargo directly, it uses a lot of cores in parallel and the build takes about 50 seconds.

build time (for the Rust part) is comparable in my case (maybe some negligible overhead due to make itself):

```shell
make ebpf && time cargo -q build -j$(nproc)                                                                                                                
[...]                                                                                                                                           
                                                                                                                                                                                                                                        
real    0m14.510s                                                                                                                                                                                                                           
user    1m30.321s                                                                                                                                                                                                                           
sys     0m15.129s                                                                                                                                                                                                                           
```

```shell
make ebpf && time make -j$(nproc)
[...]

real    0m15.284s
user    1m29.529s
sys     0m15.368s
```

but I suspect `MAKEFLAGS` here can play a role:

```shell
make -v
GNU Make 4.4.1
Built for x86_64-redhat-linux-gnu
```

**Comment by igsilya** [comment]
> > @atenart Ack. You may treat this one as a documentation bug then, since building retis with `make` doesn't seem to be documented anywhere, AFAICT. docs/install.md says that I need to build with cargo.
> > Also, `jq` is now a build requirement and this is also not documented.
> 
> [latest doc](https://retis.readthedocs.io/en/latest/install/#from-sources) should mention both. Any chance the doc was pointing to stable (default)?

Admittedly, it was 1 a.m. when I looked at the docs, so it is possible that I looked in some wrong place, can't find it now.  :D

**Comment by igsilya** [comment]
@vlrpl here are my results:
```
[root@rhel9 retis]# make clean && make ebpf && time cargo -q build -j$(nproc)
[CLEAN] cleaning ebpf progs...
[CLEAN] cleaning retis ...
[PROBE] building /root/retis/src/core/probe/kernel/bpf ...
[PROBE] building /root/retis/src/core/probe/user/bpf ...
[HOOK]  building /root/retis/src/module/skb/bpf ...
[HOOK]  building /root/retis/src/module/skb_drop/bpf ...
[HOOK]  building /root/retis/src/module/skb_tracking/bpf ...
[HOOK]  building /root/retis/src/module/nft/bpf ...
[HOOK]  building /root/retis/src/module/ct/bpf ...
[HOOK]  building /root/retis/src/module/ovs/bpf ...

real    0m39.593s
user    3m55.454s
sys     0m20.082s
[root@rhel9 retis]# 
[root@rhel9 retis]# 
[root@rhel9 retis]# 
[root@rhel9 retis]# 
[root@rhel9 retis]# 
[root@rhel9 retis]# make clean && make ebpf && time make -j$(nproc)
[CLEAN] cleaning ebpf progs...
[CLEAN] cleaning retis ...
[PROBE] building /root/retis/src/core/probe/kernel/bpf ...
[PROBE] building /root/retis/src/core/probe/user/bpf ...
[HOOK]  building /root/retis/src/module/skb/bpf ...
[HOOK]  building /root/retis/src/module/skb_drop/bpf ...
[HOOK]  building /root/retis/src/module/skb_tracking/bpf ...
[HOOK]  building /root/retis/src/module/nft/bpf ...
[HOOK]  building /root/retis/src/module/ct/bpf ...
[HOOK]  building /root/retis/src/module/ovs/bpf ...
[PROBE] building /root/retis/src/core/probe/kernel/bpf ...
[PROBE] building /root/retis/src/core/probe/user/bpf ...
[HOOK]  building /root/retis/src/module/skb/bpf ...
[HOOK]  building /root/retis/src/module/skb_drop/bpf ...
[HOOK]  building /root/retis/src/module/skb_tracking/bpf ...
[HOOK]  building /root/retis/src/module/nft/bpf ...
[HOOK]  building /root/retis/src/module/ct/bpf ...
[HOOK]  building /root/retis/src/module/ovs/bpf ...
[CARGO] building retis (debug) ...

real    3m34.710s
user    3m21.304s
sys     0m14.737s
```

40 seconds vs 3.5 minutes.
And I don't know why hooks are built twice with make.

```
[root@rhel9 ~]# make -v
GNU Make 4.3
Built for x86_64-redhat-linux-gnu
[root@rhel9 ~]# cargo --version
cargo 1.71.1
[root@rhel9 ~]# rustc --version
rustc 1.71.1 (eb26296b5 2023-08-03) (Red Hat 1.71.1-1.el9)
```

**Comment by igsilya** [comment]
> And I don't know why hooks are built twice with make. (I guess, make re--builds them.)

They are not actually re-built, the make just lists the steps.

**Comment by vlrpl** [comment]
> > And I don't know why hooks are built twice with make. (I guess, make re--builds them.)
> 
> They are not actually re-built, the make just lists the steps.

yes, they're just printouts in case the prereq is up to date

**Comment by igsilya** [comment]
Parallel build works fine on Fedora 38 though:
```
$ make -v
GNU Make 4.4.1
$ cargo --version
cargo 1.76.0
```

So, works on Fedora 38 (make 4.4, rust 1.76) and doesn't work on RHEL9 (make 4.3, rust 1.71) and Ubuntu 23.04 (make 4.3, rust 1.70).

**Comment by vlrpl** [comment]
> > 40 seconds vs 3.5 minutes.
> 
> I see a very similar thing on Ubuntu 23.04 as well.

I confirm my initial suspicion. It is related to $(MAKEFLAGS). On my version contains `-j<n>` during the step $(JOBS) gets detected, but on rhel9 (and now on Ubuntu) it doesn't.

**Comment by vlrpl** [comment]
Thanks @igsilya!
I slightly edited the patch (missing options to sed), but in general this probably
needs some modifications anyways.

Let's keep this bug to track the parallel issue.
